# -*- coding: utf-8 -*-
"""train_aug_split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bnhz-Mdmj0CJagQrfLGZY8aYK4sPIllT
"""

import numpy as np
import pandas as pd
from PIL import Image
import torchvision.transforms as T

images_train = np.load("/content/drive/MyDrive/val_train_split/images_trainval.npy")
pvls_train = np.load("/content/drive/MyDrive/val_train_split/pv_log_trainval.npy")

weather_train = pd.read_csv(
    "/content/drive/MyDrive/val_train_split/trainval_phys_3calsses"
)

weather_train_list = list(weather_train["weather"])

"""augmentation starts"""

preprocess = T.Compose(
    [
        T.ToTensor(),
        T.RandomHorizontalFlip(p=0.5),
        T.RandomRotation(degrees=45),
        T.RandomVerticalFlip(p=0.05),
        T.ColorJitter(brightness=0.5, contrast=0.5),
    ]
)

image_train_ = list(images_train)
pvls_train_ = list(pvls_train)
weather_train_2 = weather_train_list

for i in range(len(image_train_)):
    copy_1 = image_train_[i]
    pil_image = Image.fromarray(copy_1)
    x = preprocess(pil_image)
    CT = T.ToPILImage()
    img = CT(x)
    imgnew = np.array(img)
    image_train_.append(imgnew)
    weather_train_2.append(weather_train_2[i])
    pvls_train_.append(pvls_train_[i])

image_train_ = np.array(image_train_)
pvls_train_ = np.array(pvls_train_)

weather_train_2 = pd.DataFrame(weather_train_2, columns=["weather"])

np.save("/content/drive/MyDrive/aug_dataset/images_trainval.npy", image_train_)

np.save("/content/drive/MyDrive/aug_dataset/pv_log_trainval.npy", pvls_train_)

weather_train_2.to_csv(
    "/content/drive/MyDrive/aug_dataset/trainval_phys_3calsses", index=False
)
