# -*- coding: utf-8 -*-
"""val_train_split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cfJZR1F5e2JUC-zOUbEKVKWCfe-Txb5F
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

images_train = np.load("/content/drive/MyDrive/asdf/photovoltaics/images_trainval.npy")
pvls_train = np.load("/content/drive/MyDrive/asdf/photovoltaics/pv_log_trainval.npy")

weather_train = pd.read_csv(
    "/content/Photovoltaic-power-and-solar-radiation-forecasting/trainval_phys_3calsses"
)

weather_train_list = list(weather_train["sunny"])
weather_train_list.insert(0, "sunny")

weather_train_1 = pd.DataFrame(weather_train_list, columns=["weather"])

image_train_, image_val, pvls_train_, pvls_val = train_test_split(
    images_train, pvls_train, train_size=0.9, test_size=0.1, random_state=42
)

_, _, weather_train_2, weather_val = train_test_split(
    images_train, weather_train_1, train_size=0.9, test_size=0.1, random_state=42
)

np.save("/content/drive/MyDrive/val_train_split/images_trainval.npy", image_train_)

np.save("/content/drive/MyDrive/val_train_split/images_val.npy", image_val)

np.save("/content/drive/MyDrive/val_train_split/pv_log_trainval.npy", pvls_train_)

np.save("/content/drive/MyDrive/val_train_split/pv_log_val.npy", pvls_val)

weather_train_2.to_csv(
    "/content/drive/MyDrive/val_train_split/trainval_phys_3calsses", index=False
)

weather_val.to_csv(
    "/content/drive/MyDrive/val_train_split/val_phys_3calsses", index=False
)
